### ISSUE TITLE
Message authentication code incorrect

### ISSUE THREAD

**Issue by myfoxx** [RealityNet/ios_bfu_triage#2]
Hi
good job!!!

I report a problem, even if it is not directly related to the script.
In the  Full acquisition after a few seconds the ssh session ends  with this error.

```
sshpass -p alpine ssh root@127.0.0.1 tar -cf - / > full.tar
tar: Removing leading `/' from member names
tar: Removing leading `//' from member names
tar: /.fseventsd: Cannot open: Operation not permitted
Corrupted MAC on input.
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 22: message authentication code incorrect

```

**Comment by mattiaepi** [comment]
Hi myfoxx,
thanks for your comment.

I tried to replicate your issue but I was not able to do it.

We only tested the script on Mac OS X.

Are you working on a Mac or on a Linux machine?
Can you try with a different computer (and evntually with a different phone)?

Thanks and have a great day

**Comment by myfoxx** [comment]
Sorry for the late reply .. holidays don't help !!
I did the test with a MAC
However I will try in the next few days with another phone and let you know if it happens again.

Thank you !
